spring:
  application:
    name: demo
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/paint
    username: postgres
    password: 1234
